service: home

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:Query"
       - "dynamodb:Scan"
     Resource: "arn:aws:dynamodb:*:*:table/*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  energyconsumption-list:
    handler: bin/energyconsumption/list
    events:
      - http:
          path: energyconsumption/list
          method: get
